### ISSUE TITLE
(제안) 타 라이선스로의 변경

### ISSUE THREAD

**Issue by handbros** [gramedcart/mvextractor#1]
CCL은 일반적으로 글, 그림 등의 창작물에서 주로 사용되는 라이선스인지라 소프트웨어 분야에서는 사용하기 애매한 부분이 있습니다.
가장 대표적으로는 법적 보증 부인(Disclaimer, 면책조항)에 관한 내용이 빠져있다는 점이겠네요.
혹시 모를 법적 분쟁을 피하기 위해서라도 AS-IS 상태로 배포한다는걸 명시하는 라이선스를 채택하시는게 좋습니다.

대표적으로는 MIT, BSD 3-clause, Apache, GPL 등의 라이선스가 있는데, 개인적으로는 MIT 라이선스를 추천드립니다 :)
@gramedcart @anberry87

**Comment by gramedcart** [comment]
MIT 라이센스로 변경 해볼까 생각 중입니다
