### ISSUE TITLE
적용모드 시도하니 이런에러가 발생합니다

### ISSUE THREAD

**Issue by LeePC** [gramedcart/mvextractor#2]
{"stack":"Error: ENOENT: no such file or directory, open './test/ed.json'\n at Object.openSync (node:fs:585:3)\n at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)\n at Object.writeFileSync (node:fs:2153:35)\n at IpcMainImpl.exports.apply (C:\\Users\\akrrk\\Documents\\mvextractor-main\\src\\js\\apply.js:47:12)\n at IpcMainImpl.emit (node:events:390:28)\n at EventEmitter. (node:electron/js2c/browser_init:161:10780)\n at EventEmitter.emit (node:events:390:28)","message":"ENOENT: no such file or directory, open './test/ed.json'","errno":-4058,"syscall":"open","code":"ENOENT","path":"./test/ed.json"}
도대체 왜이럴까요
파파고로 번역한뒤 시도한상태입니다

**Comment by gramedcart** [comment]
테스트 할때 만든 스크립트가 빠지지 않아서 오류를 일으킨 것 같습니다. 
1.13.1에 수정하겠습니다
